package com.scheduler.services;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.BadSqlGrammarException;
import org.springframework.stereotype.Component;

import com.scheduler.mappers.NotificationMapper;
import com.scheduler.models.Notification;
import com.scheduler.request.SendPostRequest;

@Component
public class NotificationService {

	@Autowired(required = true)
	private NotificationMapper notificationMapper;

	// Author - Sonny
	/* Get the user id, and and send a notification
	 * 1. Push notification
	 * 2. Add new row to notification table
	 */
	public boolean notifyUser(String registration_id, Notification notification) {

		// push notification to mobile device
		String title = notification.getNotificationHeader();
		String message = notification.getNotificationDescription();
		SendPostRequest p = new SendPostRequest();
		// Value generated by the sendNotification function is throwing java.sql.SQLException: Data truncated for column
		String message_id = p.sendNotification(registration_id, title, message);

		// add message_id to the notification object
		notification.setGcmMessageId(message_id);
		
		
		System.out.println(notification.getGcmMessageId()); 
		
		// insert a row in notifications table
		int createdNotificationId = addNewNotification(notification);
		if(createdNotificationId > 0)
			return true;
		else
			return false;
	}
	
	public int addNewNotification(Notification notification) 
	{
		return notificationMapper.addNewNotification(notification);
	}
	
	public List<Notification> findAllNotifications(int userId) throws BadSqlGrammarException{
		return notificationMapper.findAllNotifications(userId);
		
	}

}
